### ISSUE TITLE
Code no longer works with latest Tumblr

### ISSUE THREAD

**Issue by billramo** [jefflomax/powershell-download-tumbler-images#1]
Tumblr has since gone to an API model - [https://www.tumblr.com/docs/en/api/v2](url) that requires OAuth authentication for performing full downloads. If you are using the site URL, your limited to the number of images you can get.

In addition, the images are now located in the <script> window.launcher section of the page that Invoke-WebRequest returns in the Content response.

**Comment by jefflomax** [comment]
You would always have to adapt to your site's template, the code remains as instructive as ever.
